/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import com.mysql.jdbc.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import proyecto.Conexion;

/**
 *
 * @author TOSHIBA
 */
public class ModuloLibros extends javax.swing.JFrame {
 
    
 
    private      Conexion db = new Conexion();
    private  Connection cn = db.MySQLConnect();
    private PreparedStatement pst=null;
    private ResultSet r = null;
    
    private int cont = 0;
    private int cont1 = 0;
    private int Total,valor,subTotal;
    /**
     * Creates new form NewJFrame
     */
    public ModuloLibros() {
        initComponents();
        setTitle("Modulo libros");
        setLocationRelativeTo(null);
        txtNombreLibro.requestFocus();
        txtAreaDes.setLineWrap(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        pnlControl = new javax.swing.JPanel();
        btnIngresar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        pnlDatos = new javax.swing.JPanel();
        PnlDatosG = new javax.swing.JPanel();
        lblIdLibro = new java.awt.Label();
        txtIdLibro = new java.awt.TextField();
        lblNombre = new java.awt.Label();
        txtNombreLibro = new java.awt.TextField();
        lblAutor = new java.awt.Label();
        txtAutor = new java.awt.TextField();
        lblEditorial = new java.awt.Label();
        txtEditorial = new java.awt.TextField();
        lblCExistente = new java.awt.Label();
        txtCExistente = new java.awt.TextField();
        lblCTotal = new java.awt.Label();
        txtCTotal = new java.awt.TextField();
        lblDescripcion = new java.awt.Label();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaDes = new javax.swing.JTextArea();
        lblTitulo = new java.awt.Label();
        pnlBuscar = new javax.swing.JPanel();
        lblObBuscar = new java.awt.Label();
        txtBuscar = new java.awt.TextField();
        btnBuscar = new javax.swing.JButton();
        btnPrim = new javax.swing.JButton();
        btnUlt = new javax.swing.JButton();
        btnSig = new javax.swing.JButton();
        BtnAnt = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();
        menuPrincipal = new javax.swing.JMenuBar();
        menuOpciones = new javax.swing.JMenu();
        SubmenuRegresar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        submenuSalir = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Modulo Libros");
        setResizable(false);

        pnlControl.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlControlLayout = new javax.swing.GroupLayout(pnlControl);
        pnlControl.setLayout(pnlControlLayout);
        pnlControlLayout.setHorizontalGroup(
            pnlControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlControlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnIngresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnActualizar)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        pnlControlLayout.setVerticalGroup(
            pnlControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlControlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnIngresar)
                    .addComponent(btnEliminar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlDatos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        PnlDatosG.setBackground(new java.awt.Color(51, 255, 102));
        PnlDatosG.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Datos generales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 0, 204))); // NOI18N

        lblIdLibro.setText("ID del Libro:");

        txtIdLibro.setEditable(false);
        txtIdLibro.setEnabled(false);

        lblNombre.setText("Nombre:");

        txtNombreLibro.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        lblAutor.setText("Autor:");

        lblEditorial.setText("Editorial:");

        lblCExistente.setText("Cantidad existente:");

        txtCExistente.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCExistente.setEditable(false);
        txtCExistente.setEnabled(false);

        lblCTotal.setText("Cantidad total:");

        txtCTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCTotalActionPerformed(evt);
            }
        });

        lblDescripcion.setText("Descripción:");

        txtAreaDes.setColumns(20);
        txtAreaDes.setRows(5);
        jScrollPane2.setViewportView(txtAreaDes);

        javax.swing.GroupLayout PnlDatosGLayout = new javax.swing.GroupLayout(PnlDatosG);
        PnlDatosG.setLayout(PnlDatosGLayout);
        PnlDatosGLayout.setHorizontalGroup(
            PnlDatosGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlDatosGLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(PnlDatosGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCExistente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PnlDatosGLayout.createSequentialGroup()
                        .addGroup(PnlDatosGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIdLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(73, 73, 73)
                        .addGroup(PnlDatosGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCExistente, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PnlDatosGLayout.createSequentialGroup()
                        .addComponent(lblDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblCTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        PnlDatosGLayout.setVerticalGroup(
            PnlDatosGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlDatosGLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlDatosGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIdLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlDatosGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombreLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlDatosGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlDatosGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlDatosGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCExistente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCExistente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlDatosGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlDatosGLayout.createSequentialGroup()
                        .addComponent(lblCTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(PnlDatosGLayout.createSequentialGroup()
                        .addComponent(txtCTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        lblTitulo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblTitulo.setText("Libros");

        javax.swing.GroupLayout pnlDatosLayout = new javax.swing.GroupLayout(pnlDatos);
        pnlDatos.setLayout(pnlDatosLayout);
        pnlDatosLayout.setHorizontalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosLayout.createSequentialGroup()
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(246, 246, 246))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosLayout.createSequentialGroup()
                        .addComponent(PnlDatosG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))))
        );
        pnlDatosLayout.setVerticalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(PnlDatosG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
        );

        pnlBuscar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblObBuscar.setText("Dato a buscar:");

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnPrim.setText("<<");
        btnPrim.setEnabled(false);
        btnPrim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimActionPerformed(evt);
            }
        });

        btnUlt.setText(">>");
        btnUlt.setEnabled(false);
        btnUlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltActionPerformed(evt);
            }
        });

        btnSig.setText(">");
        btnSig.setEnabled(false);
        btnSig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSigActionPerformed(evt);
            }
        });

        BtnAnt.setText("<");
        BtnAnt.setEnabled(false);
        BtnAnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAntActionPerformed(evt);
            }
        });

        lblResultado.setText("0 de 0");

        javax.swing.GroupLayout pnlBuscarLayout = new javax.swing.GroupLayout(pnlBuscar);
        pnlBuscar.setLayout(pnlBuscarLayout);
        pnlBuscarLayout.setHorizontalGroup(
            pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBuscarLayout.createSequentialGroup()
                        .addGroup(pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBuscarLayout.createSequentialGroup()
                                .addComponent(lblObBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlBuscarLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(btnPrim)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnAnt)
                                .addGap(18, 18, 18)
                                .addComponent(btnSig)))
                        .addGroup(pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBuscarLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(btnBuscar))
                            .addGroup(pnlBuscarLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnUlt))))
                    .addGroup(pnlBuscarLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        pnlBuscarLayout.setVerticalGroup(
            pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscar)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblObBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrim)
                    .addComponent(btnSig)
                    .addComponent(btnUlt)
                    .addComponent(BtnAnt))
                .addGap(25, 25, 25))
        );

        menuOpciones.setText("Opciones");

        SubmenuRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/regresar.jpg"))); // NOI18N
        SubmenuRegresar.setText("Regresar");
        SubmenuRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmenuRegresarActionPerformed(evt);
            }
        });
        menuOpciones.add(SubmenuRegresar);
        menuOpciones.add(jSeparator1);

        submenuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Exit.jpg"))); // NOI18N
        submenuSalir.setText("Salir");
        submenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenuSalirActionPerformed(evt);
            }
        });
        menuOpciones.add(submenuSalir);

        menuPrincipal.add(menuOpciones);

        setJMenuBar(menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(pnlDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(pnlControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(pnlDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(430, 430, 430)
                        .addComponent(pnlControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_submenuSalirActionPerformed

    private void SubmenuRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmenuRegresarActionPerformed
        // TODO add your handling code here:
        Principal ventana = new Principal();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_SubmenuRegresarActionPerformed
    private void    BuscarId(){
        try {
            pst=cn.prepareStatement("SELECT `idLibro` FROM `libro`");
            r=pst.executeQuery();
            r.last();
             valor=Integer.parseInt(r.getString("idLibro"));
        } catch (SQLException ex) {
            Logger.getLogger(ModuloLibros.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private  void insertar() {
        
 BuscarId();
        
        
        
        try {
            // TODO add your handling code here:
            
 
            
            if (!txtNombreLibro.getText().equals("") && !txtCTotal.getText().equals("")) {
               if(txtAutor.getText().equals("")){
              txtAutor.setText("Desconocido");
               }
               
                   pst = cn.prepareStatement("INSERT INTO `libro`(`Nombre`, `Autor`, `Editorial`,  `Cantidad_Existente`, `Cantidad_Total`, `Descripcion`) VALUES (?,?,?,?,?,?)");

                pst.setString(1, txtNombreLibro.getText());
                pst.setString(2, txtAutor.getText());
                pst.setString(3, txtEditorial.getText());
              

                pst.setInt(4, Integer.parseInt(txtCTotal.getText()));
                pst.setInt(5, Integer.parseInt(txtCTotal.getText()));
                pst.setString(6, txtAreaDes.getText());
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Los datos se registraron correctamente con el id: "+(valor+1) , "Exito", 1);
            } else {
                JOptionPane.showMessageDialog(null, "Revise los campos, (NOMBRE,TOTAL-LIBROS)", "Error", 0);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ModuloLibros.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        if(txtIdLibro.getText().equals("")){
        insertar();
        
        }
        else{
              cont=0;
      inhabilitar();
         JOptionPane.showMessageDialog(null, "Libro ya existente", "Error", 0);

        }
        Limpiar();
    }//GEN-LAST:event_btnIngresarActionPerformed
public void Buscar(){
     try {
            // TODO add your handling code here:
            pst = cn.prepareStatement("SELECT * FROM `libro` WHERE `IdLibro` LIKE ? OR `Nombre`LIKE ?");
            //(txtBuscar.getText())
            
            String vr = "%" + txtBuscar.getText() + "%";
            pst.setString(1, txtBuscar.getText());
            pst.setString(2, vr);
            r = pst.executeQuery();

            //ResultSet res = new Data();
            cont = 0;
            while (r.next()) {
                cont++;

                /* Pruebas Manuales 
          
                 */
            }
            if (cont == 0) {
                JOptionPane.showMessageDialog(null, "No se encontro algun resutaldo con la referencia " + txtBuscar.getText(), "Error", 0);
                Limpiar();
            } else {
                if (r.first()) {
                    cont1 = 1;
                    Campos();

                }
                inhabilitar();
            }
        } catch (SQLException ex) {
            Logger.getLogger(ModuloLibros.class.getName()).log(Level.SEVERE, null, ex);
        }


}
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
if(!txtBuscar.getText().equals("")){
    Buscar();
    txtBuscar.setText("");
}
else{
                    JOptionPane.showMessageDialog(null, "No ingreso nada a buscar" , "Error", 0);

}
       
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnSigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSigActionPerformed
        try {
            // TODO add your handling code here:
            if (r.next()) {
                cont1++;
                Campos();
             
            }
            inhabilitar();
        } catch (SQLException ex) {
            Logger.getLogger(ModuloLibros.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSigActionPerformed

    private void BtnAntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAntActionPerformed
        try {
            // TODO add your handling code here:
            if (r.previous()) {
                cont1--;
                Campos();
            }
            inhabilitar();
        } catch (SQLException ex) {
            Logger.getLogger(ModuloLibros.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnAntActionPerformed
//sql call almuser(Texbo1,Texbo2,Texbo3);
    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnPrimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimActionPerformed
        try {
            // TODO add your handling code here:

            if (r.first()) {
                cont1 = 1;
                Campos();
                
            }
            inhabilitar();
        } catch (SQLException ex) {
            Logger.getLogger(ModuloLibros.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPrimActionPerformed

    private void btnUltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltActionPerformed
        try {
            // TODO add your handling code here:

            if (r.last()) {
               
                cont1 = cont;
                 Campos();
            }
            inhabilitar();
        } catch (SQLException ex) {
            Logger.getLogger(ModuloLibros.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUltActionPerformed
private void Eliminar(){
       
        try {
            pst=cn.prepareStatement("DELETE FROM `libro` WHERE `IdLibro` = ?");
            
            pst.setString(1, txtIdLibro.getText());
            pst.executeUpdate(); 
            JOptionPane.showMessageDialog(null, "Eliminado", "Ok", 1);
        } catch (SQLException ex) {
            Logger.getLogger(ModuloLibros.class.getName()).log(Level.SEVERE, null, ex);
        }
}
private void EliminarUno(){
      
        try { Total--;
              subTotal--;
            pst=cn.prepareCall("UPDATE `libro` SET `Cantidad_Existente`=?,`Cantidad_Total`=? WHERE `idLibro` like ?");
        
                  pst.setInt(1, subTotal);
                  pst.setInt(2, Total);
                  pst.setString(3, txtIdLibro.getText());
                
                  pst.executeUpdate();
                   JOptionPane.showMessageDialog(null, "Se elimino 1", "ok", 1);
        } catch (SQLException ex) {
            Logger.getLogger(ModuloLibros.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        Object[] options = {"Todo"," 1 Registro","Cancelar"};
        int msg = JOptionPane.showOptionDialog(null,"¿Que opcion le desea Ejecutar?",  "Titulo",
                JOptionPane.YES_NO_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE,null,options, options[2]);
        if(msg==JOptionPane.OK_OPTION && !txtIdLibro.getText().equals("")){
            if(subTotal==Total){
                Eliminar();
                
                Limpiar();
            }
             else if( subTotal==0){
                JOptionPane.showMessageDialog(null, "No se pudo eliminar por cuestiones de que hay libros "
                        + "prestados con su referencia", "", 0);
                 Limpiar();
            }
            else{
                EliminarUno();
                 Limpiar();
            }
        }
        else if(msg==JOptionPane.NO_OPTION && !txtIdLibro.getText().equals("")) {
            if(Total>1 && subTotal>0){
                EliminarUno();
                Limpiar();
            }
            else if(Total>1 && subTotal==0){
                JOptionPane.showMessageDialog(null, "No se pudo eliminar por cuestiones de que hay libros "
                        + "prestados con su referencia", "", 0);
                 Limpiar();
            }
            else{
                Eliminar();
                Limpiar();
            }
            
        }
        
        
        else{
            JOptionPane.showMessageDialog(null, "No eliminado","Error",0);
            
        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        try {
            // TODO add your handling code here:
          
           if(!txtIdLibro.getText().equals("")){
               pst = cn.prepareStatement("UPDATE `libro`SET `Nombre`=?, `Autor`=?,"
                       + " `Editorial`=?,  `Cantidad_Existente`=?, `Cantidad_Total`=?, `Descripcion`=?"
                       + " WHERE `idLibro` like ?");
           
       

                pst.setString(1, txtNombreLibro.getText());
                pst.setString(2, txtAutor.getText());
                pst.setString(3, txtEditorial.getText());
                pst.setInt(4, Integer.parseInt(txtCTotal.getText()));
                pst.setInt(5, Integer.parseInt(txtCTotal.getText()));
                pst.setString(6, txtAreaDes.getText());
                pst.setInt(7, Integer.parseInt(txtIdLibro.getText()));
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Los datos se modificaron correctamente", "Exito", 1);
                 Limpiar();
           }
           else{
               JOptionPane.showMessageDialog(null, "Verifique los datos a Actualizar", "Error", 0);
           }
              
           } catch (SQLException ex) {
            Logger.getLogger(ModuloLibros.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void txtCTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModuloLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModuloLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModuloLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModuloLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModuloLibros().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAnt;
    private javax.swing.JPanel PnlDatosG;
    private javax.swing.JMenuItem SubmenuRegresar;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnPrim;
    private javax.swing.JButton btnSig;
    private javax.swing.JButton btnUlt;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private java.awt.Label lblAutor;
    private java.awt.Label lblCExistente;
    private java.awt.Label lblCTotal;
    private java.awt.Label lblDescripcion;
    private java.awt.Label lblEditorial;
    private java.awt.Label lblIdLibro;
    private java.awt.Label lblNombre;
    private java.awt.Label lblObBuscar;
    private javax.swing.JLabel lblResultado;
    private java.awt.Label lblTitulo;
    private javax.swing.JMenu menuOpciones;
    private javax.swing.JMenuBar menuPrincipal;
    private javax.swing.JPanel pnlBuscar;
    private javax.swing.JPanel pnlControl;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JMenuItem submenuSalir;
    private javax.swing.JTextArea txtAreaDes;
    private java.awt.TextField txtAutor;
    private java.awt.TextField txtBuscar;
    private java.awt.TextField txtCExistente;
    private java.awt.TextField txtCTotal;
    private java.awt.TextField txtEditorial;
    private java.awt.TextField txtIdLibro;
    private java.awt.TextField txtNombreLibro;
    // End of variables declaration//GEN-END:variables

    private void Campos() {
        try {
            txtIdLibro.setText(r.getString("idLibro"));

            txtNombreLibro.setText(r.getString("Nombre"));
            txtAutor.setText(r.getString("Autor"));
            txtEditorial.setText(r.getString("Editorial"));
            
           
            
           
            txtCExistente.setText(r.getString("Cantidad_Existente"));
            subTotal=Integer.parseInt(r.getString("Cantidad_Existente"));
            txtCTotal.setText(r.getString("Cantidad_Total"));
            Total=Integer.parseInt(r.getString("Cantidad_Total"));
            txtAreaDes.setText(r.getString("Descripcion"));
           // (8 de 8)
            lblResultado.setText(cont1 + " de " + cont);
        } catch (SQLException ex) {
            Logger.getLogger(ModuloLibros.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public  void inhabilitar() {
        try {
            if (cont <= 1) {
                btnUlt.setEnabled(false);
                btnPrim.setEnabled(false);
                BtnAnt.setEnabled(false);
                btnSig.setEnabled(false);
            } else {
                if (r.isFirst()) {
                    btnUlt.setEnabled(true);
                    btnPrim.setEnabled(false);
                    BtnAnt.setEnabled(false);
                    btnSig.setEnabled(true);
                } else {
                    if (r.isLast()) {
                        btnUlt.setEnabled(false);
                        btnPrim.setEnabled(true);
                        BtnAnt.setEnabled(true);
                        btnSig.setEnabled(false);
                    } else  {
                        btnUlt.setEnabled(true);
                        btnPrim.setEnabled(true);
                        BtnAnt.setEnabled(true);
                        btnSig.setEnabled(true);
                    }
                   
                }
            }

        } catch (SQLException ex) {
            Logger.getLogger(ModuloLibros.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void Limpiar() {

        txtIdLibro.setText("");
        txtNombreLibro.setText("");
        txtAutor.setText("");
        txtEditorial.setText("");
        
        txtCExistente.setText("");
        txtCTotal.setText("");
        txtAreaDes.setText("");
        lblResultado.setText("0 de 0");
    }
}
