/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import com.mysql.jdbc.Connection;
import java.awt.ComponentOrientation;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import proyecto.Conexion;

/**
 *
 * @author TOSHIBA
 */
public class ModuloFormato extends javax.swing.JFrame {
 private      Conexion db = new Conexion();
    private  Connection cn = db.MySQLConnect();
    private PreparedStatement pst=null;
    private ResultSet r = null;
    private int valor, cont=0, contar=0, CanLibro, boton=1;
    private boolean limpieza, exis;
;
    private          SimpleDateFormat formateador = new SimpleDateFormat("yyyy-MM-dd");
private  String fecha;
    
    /**
     * Creates new form NewJFrame
     */
    public ModuloFormato() {
        initComponents();
        setTitle("Modulo Formato de salida");
        setLocationRelativeTo(null);
        txtIdUser.requestFocus();
        listaEstado.addItem("Prestado");
        listaEstado.addItem("Devuelto");
        listaEstado.addItem("Perdido");
      listaObEntrada.addItem("");
        listaObEntrada.addItem("Buenas Condiciones");
        listaObEntrada.addItem("Malas Condiciones");
        listaObSalida.addItem("Buenas Condiciones");
        listaObSalida.addItem("Malas Condiciones");
        
   

         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBuscar3 = new javax.swing.JPanel();
        lblObBuscar3 = new java.awt.Label();
        txtBuscar = new java.awt.TextField();
        btnBuscar = new javax.swing.JButton();
        btnPrim = new javax.swing.JButton();
        btnUlt = new javax.swing.JButton();
        btnSig = new javax.swing.JButton();
        BtnAnt = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();
        pnlCompto = new javax.swing.JPanel();
        PnlDatosG = new javax.swing.JPanel();
        lblIdPrestamo = new java.awt.Label();
        txtIdPrestamo = new java.awt.TextField();
        lblIdUser = new java.awt.Label();
        txtIdUser = new java.awt.TextField();
        lblFSalida = new java.awt.Label();
        txtFSalida = new java.awt.TextField();
        lblTitulo = new java.awt.Label();
        PnlDetalles = new javax.swing.JPanel();
        txtFEntrada = new com.toedter.calendar.JDateChooser();
        lblIdLibro = new java.awt.Label();
        txtIdLibro = new java.awt.TextField();
        lblFEntrada = new java.awt.Label();
        lblObSalida = new java.awt.Label();
        lblObEntrada = new java.awt.Label();
        lblEstado = new java.awt.Label();
        listaEstado = new javax.swing.JComboBox<>();
        listaObSalida = new javax.swing.JComboBox<>();
        listaObEntrada = new javax.swing.JComboBox<>();
        pnlControl = new javax.swing.JPanel();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnIngresar = new javax.swing.JButton();
        btnTermino = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFormato = new javax.swing.JMenu();
        SubmenuRegresar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        submenuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        pnlBuscar3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblObBuscar3.setText("Dato a buscar:");

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnPrim.setText("<<");
        btnPrim.setEnabled(false);
        btnPrim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimActionPerformed(evt);
            }
        });

        btnUlt.setText(">>");
        btnUlt.setEnabled(false);
        btnUlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltActionPerformed(evt);
            }
        });

        btnSig.setText(">");
        btnSig.setEnabled(false);
        btnSig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSigActionPerformed(evt);
            }
        });

        BtnAnt.setText("<");
        BtnAnt.setEnabled(false);
        BtnAnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAntActionPerformed(evt);
            }
        });

        lblResultado.setText("0 de 0");

        javax.swing.GroupLayout pnlBuscar3Layout = new javax.swing.GroupLayout(pnlBuscar3);
        pnlBuscar3.setLayout(pnlBuscar3Layout);
        pnlBuscar3Layout.setHorizontalGroup(
            pnlBuscar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscar3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBuscar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBuscar3Layout.createSequentialGroup()
                        .addGroup(pnlBuscar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBuscar3Layout.createSequentialGroup()
                                .addComponent(lblObBuscar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlBuscar3Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(btnPrim)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnAnt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSig)))
                        .addGroup(pnlBuscar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBuscar3Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(btnBuscar))
                            .addGroup(pnlBuscar3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnUlt))))
                    .addGroup(pnlBuscar3Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        pnlBuscar3Layout.setVerticalGroup(
            pnlBuscar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscar3Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBuscar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblObBuscar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBuscar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrim)
                    .addComponent(BtnAnt)
                    .addComponent(btnSig)
                    .addComponent(btnUlt))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlCompto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlCompto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlCompto.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        pnlCompto.setFocusTraversalPolicyProvider(true);

        PnlDatosG.setBackground(new java.awt.Color(204, 255, 204));
        PnlDatosG.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Datos del prestamo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 0, 204))); // NOI18N

        lblIdPrestamo.setText("ID del Prestamo:");

        txtIdPrestamo.setEditable(false);
        txtIdPrestamo.setEnabled(false);
        txtIdPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdPrestamoActionPerformed(evt);
            }
        });

        lblIdUser.setText("ID del Usuario:");

        txtIdUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdUserActionPerformed(evt);
            }
        });

        lblFSalida.setText("Fecha de salida:");

        txtFSalida.setEditable(false);
        txtFSalida.setEnabled(false);
        txtFSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFSalidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlDatosGLayout = new javax.swing.GroupLayout(PnlDatosG);
        PnlDatosG.setLayout(PnlDatosGLayout);
        PnlDatosGLayout.setHorizontalGroup(
            PnlDatosGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlDatosGLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlDatosGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PnlDatosGLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(PnlDatosGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIdPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIdUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(PnlDatosGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(txtIdUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(152, 152, 152))
                    .addGroup(PnlDatosGLayout.createSequentialGroup()
                        .addComponent(lblFSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtFSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127))))
        );
        PnlDatosGLayout.setVerticalGroup(
            PnlDatosGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlDatosGLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(PnlDatosGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIdPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlDatosGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIdUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlDatosGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        lblTitulo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblTitulo.setText("Formato del prestamo");

        PnlDetalles.setBackground(new java.awt.Color(204, 255, 204));
        PnlDetalles.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Detalles del prestamo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 0, 204))); // NOI18N

        txtFEntrada.setDateFormatString("dd-MM-yyyy");
        txtFEntrada.setEnabled(false);

        lblIdLibro.setText("ID del libro:");

        txtIdLibro.setEnabled(false);

        lblFEntrada.setText("Fecha de entrada:");

        lblObSalida.setText("Observaciones de salida:");

        lblObEntrada.setText("Observaciones de entrada:");

        lblEstado.setText("Estado:");

        listaEstado.setEnabled(false);

        listaObSalida.setEnabled(false);

        listaObEntrada.setEnabled(false);

        javax.swing.GroupLayout PnlDetallesLayout = new javax.swing.GroupLayout(PnlDetalles);
        PnlDetalles.setLayout(PnlDetallesLayout);
        PnlDetallesLayout.setHorizontalGroup(
            PnlDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlDetallesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIdLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblObSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblObEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(PnlDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listaEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listaObSalida, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listaObEntrada, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PnlDetallesLayout.createSequentialGroup()
                        .addComponent(txtIdLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtFEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                .addGap(29, 29, 29))
        );
        PnlDetallesLayout.setVerticalGroup(
            PnlDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlDetallesLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(PnlDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIdLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listaEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PnlDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlDetallesLayout.createSequentialGroup()
                        .addComponent(lblObSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblObEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PnlDetallesLayout.createSequentialGroup()
                        .addComponent(listaObSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(listaObEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(194, 194, 194))
        );

        javax.swing.GroupLayout pnlComptoLayout = new javax.swing.GroupLayout(pnlCompto);
        pnlCompto.setLayout(pnlComptoLayout);
        pnlComptoLayout.setHorizontalGroup(
            pnlComptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlComptoLayout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlComptoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PnlDatosG, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(PnlDetalles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        pnlComptoLayout.setVerticalGroup(
            pnlComptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlComptoLayout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlComptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PnlDatosG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PnlDetalles, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pnlControl.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        btnTermino.setText("Termino/Detalles");
        btnTermino.setEnabled(false);
        btnTermino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlControlLayout = new javax.swing.GroupLayout(pnlControl);
        pnlControl.setLayout(pnlControlLayout);
        pnlControlLayout.setHorizontalGroup(
            pnlControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlControlLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnIngresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTermino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar)
                .addGap(18, 18, 18)
                .addComponent(btnActualizar)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        pnlControlLayout.setVerticalGroup(
            pnlControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlControlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar)
                    .addComponent(btnIngresar)
                    .addComponent(btnTermino))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuFormato.setText("Opciones");

        SubmenuRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/regresar.jpg"))); // NOI18N
        SubmenuRegresar.setText("Regresar");
        SubmenuRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmenuRegresarActionPerformed(evt);
            }
        });
        menuFormato.add(SubmenuRegresar);
        menuFormato.add(jSeparator1);

        submenuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Exit.jpg"))); // NOI18N
        submenuSalir.setText("Salir");
        submenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenuSalirActionPerformed(evt);
            }
        });
        menuFormato.add(submenuSalir);

        jMenuBar1.add(menuFormato);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(pnlControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlCompto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 369, Short.MAX_VALUE)
                .addComponent(pnlBuscar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlBuscar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlCompto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(pnlControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmenuRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmenuRegresarActionPerformed
      Principal ventana=new Principal();
      ventana.setVisible(true);
      this.setVisible(false);
      
    }//GEN-LAST:event_SubmenuRegresarActionPerformed

    private void submenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_submenuSalirActionPerformed
private void Habilitar(){
    
    if(boton==0){
        txtFEntrada.setEnabled(true);
        txtIdUser.setEnabled(false);        
        txtIdLibro.setEnabled(true);   
        listaObSalida.setEnabled(true);
}
    else{
        if(boton ==1){
            txtFEntrada.setEnabled(false);
            txtIdUser.setEnabled(true);
            txtIdLibro.setEnabled(false);
            listaObSalida.setEnabled(false);
            listaObEntrada.setEnabled(false);
            txtIdLibro.setEnabled(false);
            listaEstado.setEnabled(false);
    }
        else{
                if(boton==3){
               txtFEntrada.setEnabled(true);
            txtIdUser.setEnabled(true);
            txtIdLibro.setEnabled(true);
            listaObSalida.setEnabled(true);
            listaObEntrada.setEnabled(true);
            txtIdLibro.setEnabled(true);
            listaEstado.setEnabled(true);
            }
           
        }
    }
    boton =1;
    
} 
Date ahora = new Date();

private void InsertarPrestamo(){
    BuscarID();
        fecha= formateador.format(ahora);
  
         if(!txtIdUser.getText().equals("")){
            try { 
                pst=cn.prepareStatement("INSERT INTO `prestamos`( `Fecha_Salida`, `Persona_idPersona`) VALUES (?,?)");
                pst.setString(1, fecha);
                pst.setInt(2, Integer.parseInt(txtIdUser.getText()));
                pst.executeUpdate();
                

               Habilitar();
                btnTermino.setEnabled(true);
                JOptionPane.showMessageDialog(null, "Regsistro generado con fecha: "+ fecha +" y con este id: "+ (valor+1)  , "Ok", 1);
                txtFSalida.setText(fecha); 
                fecha="";
                  btnTermino.setEnabled(true);
            } catch (SQLException ex) {
                //Logger.getLogger(ModuloFormato.class.getName()).log(Level.SEVERE, null, ex);
                                JOptionPane.showMessageDialog(null, "Error en el registro, el ID de usuario: <<"+txtIdUser.getText()
                                        + ">> no existe o no se encuentra disponible ", "Error", 0); 
            }
            
        }
        else{
             JOptionPane.showMessageDialog(null, "Revise los campos", "Error", 0);

        }
}
private void BuscarID(){
     try {
         pst=cn.prepareStatement("SELECT `IdPrestamo` FROM `prestamos`");
         r=pst.executeQuery();
         r.last();
         valor=Integer.parseInt(r.getString("IdPrestamo"));
         
     } catch (SQLException ex) {
         Logger.getLogger(ModuloFormato.class.getName()).log(Level.SEVERE, null, ex);
     }
}
private void InsertarDetalles( ){
    
    
       
         
         BuscarID();
         BusquedaLibro();
         if(CanLibro>0 && exis==true && txtFEntrada.getDate()!=null && ahora.before(txtFEntrada.getDate())){
             try {
                 pst=cn.prepareStatement("INSERT INTO `detalles_del_prestamo`(`Prestamo_IdPrestamo`, "
                         + "`LIbro_IdLibro`, `Estado`, `Observaciones_Salida`, `Observaciones_Regreso`, `Fecha_Entrada`) "
                         + "VALUES  (?,?,?,?,?,?)");
                 pst.setInt(1,valor);
                 pst.setInt(2,Integer.parseInt( txtIdLibro.getText()));
                 pst.setString(3, (String) listaEstado.getSelectedItem());
                 pst.setString(4, (String) listaObSalida.getSelectedItem());
                 pst.setString(5, (String) listaObEntrada.getSelectedItem());
                  fecha= formateador.format(txtFEntrada.getDate());
                 pst.setString(6, fecha);
                 pst.executeUpdate();
                 CanLibro--;
                 AcLibro();
             } catch (SQLException ex) {
              
                
                 Logger.getLogger(ModuloFormato.class.getName()).log(Level.SEVERE, null, ex); 
                
             }
         
         

         }
         else{if(exis==true && txtFEntrada.getDate()!=null&& ahora.before(txtFEntrada.getDate())){
             JOptionPane.showMessageDialog(null, "No existe el libro en existencia", "", 0);
         }
         else{
              JOptionPane.showMessageDialog(null, "Revise la fecha, Fecha minima "+ahora, "", 0);
         }
       
         }
         
    
                      

       
}
private void BusquedaLibro(){
     
    
        if(!txtIdLibro.getText().equals("")){
            try {
                pst=cn.prepareStatement("SELECT `Cantidad_Existente`FROM `libro` WHERE `idLibro`=?");
                pst.setInt(1, Integer.parseInt(txtIdLibro.getText()));
                r= pst.executeQuery();
                
                
                if(r.first()){
                    CanLibro=Integer.parseInt( r.getString("Cantidad_Existente"));
                    exis=true;
                }
                else{
                    JOptionPane.showMessageDialog(null, "El libro no existe", "Error", 0);
                    exis=false;
                }   } catch (SQLException ex) {
                Logger.getLogger(ModuloFormato.class.getName()).log(Level.SEVERE, null, ex);
                

            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Revise campos", "Error", 0);
        }                    
      
         
     
    
    
}
private void AcLibro(){
     try {
         pst=cn.prepareStatement("UPDATE `libro` SET `Cantidad_Existente`=? WHERE `idLibro`=?");
         pst.setInt(1, CanLibro);
         pst.setInt(2, Integer.parseInt(txtIdLibro.getText()));
         pst.executeUpdate();
     } catch (SQLException ex) {
         Logger.getLogger(ModuloFormato.class.getName()).log(Level.SEVERE, null, ex);
     }
}
    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
  if(txtIdUser.isEnabled()==true && listaEstado.isEnabled()==true){
      JOptionPane.showMessageDialog(null, "Error, trato de ingresar el mismo formato", "", 0);
              cont=0;
      Inhabilitar();
      limpiar();
      boton=1;
      Habilitar();
  }
  else{
        boton=0;    
     if (txtIdUser.isEnabled()==true) {
         int msg= JOptionPane.showConfirmDialog(null,"¿Seguro de ingresar los datos?","",JOptionPane.OK_CANCEL_OPTION);
         if(msg==JOptionPane.OK_OPTION){
             InsertarPrestamo();
           
         }
         else {
             limpieza=false;
           limpiar();
         }
     } else {
         // Buscar();
         InsertarDetalles();
         limpieza=true;
        //txtIdLibro.requestFocus();
        limpiar();
     }
  }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnTerminoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminoActionPerformed
boton=1;       
     btnTermino.setEnabled(false);
        Habilitar();
     limpieza=false;
         limpiar();
         
    }//GEN-LAST:event_btnTerminoActionPerformed
private void    EliminarTodo(){
     try {
         pst=cn.prepareStatement("DELETE FROM `prestamos` WHERE `IdPrestamo`=?");
         pst.setInt(1,Integer.parseInt(txtIdPrestamo.getText()) );
         pst.executeUpdate();
         JOptionPane.showMessageDialog(null, "Registro Eliminado", "Ok", 1);
     } catch (SQLException ex) {
         Logger.getLogger(ModuloFormato.class.getName()).log(Level.SEVERE, null, ex);
     }
}
private void    EliminarLibro(){
     try {
         pst=cn.prepareStatement("DELETE FROM `detalles_del_prestamo` WHERE `Prestamo_IdPrestamo` =? AND `LIbro_IdLibro`=?;");
          pst.setInt(1,Integer.parseInt(txtIdPrestamo.getText()) );
          pst.setInt(2, Integer.parseInt(txtIdLibro.getText()));
          
          pst.executeUpdate();
          JOptionPane.showMessageDialog(null, "Libro eliminado del prestamo", "Ok", 1);
           limpiar();
     } catch (SQLException ex) {
         Logger.getLogger(ModuloFormato.class.getName()).log(Level.SEVERE, null, ex);
     }
    
}
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if(txtIdUser.isEnabled()==true && listaEstado.isEnabled()==true){
        Object[] options = {"Formato","Registro","Cancelar"};
    int n = JOptionPane.showOptionDialog(null,"¿Que opcion le desea Ejecutar?",  "Titulo",
            JOptionPane.YES_NO_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE,null,options, options[2]);
    if(n==JOptionPane.OK_OPTION){
            EliminarTodo();
             limpiar();
              Habilitar();
            
}
    else if(n==JOptionPane.NO_OPTION){
        EliminarLibro();
         limpiar();
          Habilitar();
    }
   
  
        }
        else{
            JOptionPane.showMessageDialog(null, "Verifique datos", "", 0);
        }
           cont=0;
      Inhabilitar();
    }//GEN-LAST:event_btnEliminarActionPerformed
    
    private void txtIdUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdUserActionPerformed

    private void txtIdPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdPrestamoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtIdPrestamoActionPerformed
private void Campos(){
     try {
         
         txtIdPrestamo.setText(r.getString("IdPrestamo"));
         txtIdUser.setText(r.getString("Persona_idPersona"));
         txtFSalida.setText(r.getString("Fecha_Salida"));
         txtIdLibro.setText(r.getString("LIbro_IdLibro"));
         listaEstado.setSelectedItem(r.getString("Estado"));
         listaObSalida.setSelectedItem(r.getString("Observaciones_Salida"));
         listaObEntrada.setSelectedItem(r.getString("Observaciones_Regreso"));
         txtFEntrada.setDate(r.getDate("Fecha_Entrada"));
         lblResultado.setText(contar+" de "+cont);
     } catch (SQLException ex) {
         Logger.getLogger(ModuloFormato.class.getName()).log(Level.SEVERE, null, ex);
     }
}
    private void BuscarDatos(){
     if(!txtBuscar.getText().equals("")){
       
        try {
         pst=cn.prepareStatement("SELECT IdPrestamo, Fecha_Salida, Persona_idPersona,LIbro_IdLibro,Estado,"
                 + "Observaciones_Salida,Observaciones_Regreso,Fecha_Entrada FROM prestamos INNER JOIN detalles_del_prestamo"
                 + " ON prestamos.IdPrestamo=detalles_del_prestamo.Prestamo_IdPrestamo WHERE IdPrestamo=?");
         pst.setInt(1, Integer.parseInt(txtBuscar.getText()));
         r=pst.executeQuery();
        cont=0;
         while(r.next()){
             cont++;
         }
         if(cont!=0 ){         
         
              if(r.first()){
                  contar=1;
             Campos  ();
         } 
            
              Habilitar();  listaEstado.setEnabled(true);
              Inhabilitar();
         }
         else{
              JOptionPane.showMessageDialog(null, "No se encontro referiencia "+txtBuscar.getText(), "Error", 0);
         
         }
             
         //JOptionPane.showMessageDialog(null, "", "", 1);
     } catch (SQLException ex) {
         Logger.getLogger(ModuloFormato.class.getName()).log(Level.SEVERE, null, ex);
     }
     }
     else{
         JOptionPane.showMessageDialog(null, "No ingreso nada", "Error", 0);
     }
    }
    private void Inhabilitar(){
        try {
            if (cont <=1) {
                btnUlt.setEnabled(false);
                btnPrim.setEnabled(false);
                BtnAnt.setEnabled(false);
                btnSig.setEnabled(false);
            } else {
                if (r.isFirst()) {
                    btnUlt.setEnabled(true);
                    btnPrim.setEnabled(false);
                    BtnAnt.setEnabled(false);
                    btnSig.setEnabled(true);
                } else {
                    if (r.isLast()) {
                        btnUlt.setEnabled(false);
                        btnPrim.setEnabled(true);
                        BtnAnt.setEnabled(true);
                        btnSig.setEnabled(false);
                    } else  {
                        btnUlt.setEnabled(true);
                        btnPrim.setEnabled(true);
                        BtnAnt.setEnabled(true);
                        btnSig.setEnabled(true);
                    }
                 
                    
                }
            }

        } catch (SQLException ex) {
            Logger.getLogger(ModuloLibros.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        boton =3;
        BuscarDatos();
      txtBuscar.setText("");

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtFSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFSalidaActionPerformed

    private void btnSigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSigActionPerformed
     try {
         // TODO add your handling code here:
         if(r.next()){
             contar++;
             Campos();
         }
         Inhabilitar();
     } catch (SQLException ex) {
         Logger.getLogger(ModuloFormato.class.getName()).log(Level.SEVERE, null, ex);
     }
    }//GEN-LAST:event_btnSigActionPerformed

    private void BtnAntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAntActionPerformed
     try {
         // TODO add your handling code here:
         if(r.previous()){
             contar--;
             Campos();
             
         }
         Inhabilitar();
     } catch (SQLException ex) {
         Logger.getLogger(ModuloFormato.class.getName()).log(Level.SEVERE, null, ex);
     }
    }//GEN-LAST:event_BtnAntActionPerformed

    private void btnPrimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimActionPerformed
     try {
         // TODO add your handling code here:
         if(r.first()){
             contar=1;
             Campos();
         }
         Inhabilitar();
     } catch (SQLException ex) {
         Logger.getLogger(ModuloFormato.class.getName()).log(Level.SEVERE, null, ex);
     }
    }//GEN-LAST:event_btnPrimActionPerformed

    private void btnUltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltActionPerformed
     try {
         // TODO add your handling code here:
         if(r.last()){
             contar=cont;
             Campos();
         }
         Inhabilitar();
         
     } catch (SQLException ex) {
         Logger.getLogger(ModuloFormato.class.getName()).log(Level.SEVERE, null, ex);
     }
    }//GEN-LAST:event_btnUltActionPerformed
private void ActualizarDetalles(){
     try {
         pst=cn.prepareStatement("UPDATE `detalles_del_prestamo` SET `LIbro_IdLibro`=?,`Estado`=?,"
                 + "`Observaciones_Regreso`=? WHERE `Prestamo_IdPrestamo`=?");
         pst.setInt(1, Integer.parseInt(txtIdLibro.getText()));
         pst.setString(2, (String) listaEstado.getSelectedItem());
         pst.setString(3, (String) listaObEntrada.getSelectedItem());

         pst.setInt(4, Integer.parseInt(txtIdPrestamo.getText()));
         pst.executeUpdate();
         if( listaEstado.getSelectedItem().equals("Devuelto")){
         CanLibro++;
         AcLibro();
     }
     } catch (SQLException ex) {
         Logger.getLogger(ModuloFormato.class.getName()).log(Level.SEVERE, null, ex);
     }
}
private  void  actualizarprestamo(){
     try {
         pst=cn.prepareStatement("UPDATE `prestamos` SET`Persona_idPersona`=? WHERE `IdPrestamo`=?");
         pst.setInt(1,Integer.parseInt(txtIdUser.getText()));
         pst.setInt(2, Integer.parseInt(txtIdPrestamo.getText()));
         pst.executeUpdate();
     } catch (SQLException ex) {
         Logger.getLogger(ModuloFormato.class.getName()).log(Level.SEVERE, null, ex);
     }
}
    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
  if(txtIdUser.isEnabled()==true && listaEstado.isEnabled()==true){
        try{
        actualizarprestamo();
        ActualizarDetalles();
        limpiar();
       
        Habilitar();
        JOptionPane.showMessageDialog(null, "Actualización ok", "Ok", 1);
          } catch (Exception ex) {
              JOptionPane.showMessageDialog(null, "Error al actualizar", "", 0);
}
      
  }
       else{
            JOptionPane.showMessageDialog(null, "Verifique datos", "", 0);
        }   cont=0;
      Inhabilitar();  
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_txtBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModuloFormato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModuloFormato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModuloFormato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModuloFormato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModuloFormato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAnt;
    private javax.swing.JPanel PnlDatosG;
    private javax.swing.JPanel PnlDetalles;
    private javax.swing.JMenuItem SubmenuRegresar;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnPrim;
    private javax.swing.JButton btnSig;
    private javax.swing.JButton btnTermino;
    private javax.swing.JButton btnUlt;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private java.awt.Label lblEstado;
    private java.awt.Label lblFEntrada;
    private java.awt.Label lblFSalida;
    private java.awt.Label lblIdLibro;
    private java.awt.Label lblIdPrestamo;
    private java.awt.Label lblIdUser;
    private java.awt.Label lblObBuscar3;
    private java.awt.Label lblObEntrada;
    private java.awt.Label lblObSalida;
    private javax.swing.JLabel lblResultado;
    private java.awt.Label lblTitulo;
    private javax.swing.JComboBox<String> listaEstado;
    private javax.swing.JComboBox<String> listaObEntrada;
    private javax.swing.JComboBox<String> listaObSalida;
    private javax.swing.JMenu menuFormato;
    private javax.swing.JPanel pnlBuscar3;
    private javax.swing.JPanel pnlCompto;
    private javax.swing.JPanel pnlControl;
    private javax.swing.JMenuItem submenuSalir;
    private java.awt.TextField txtBuscar;
    private com.toedter.calendar.JDateChooser txtFEntrada;
    private java.awt.TextField txtFSalida;
    private java.awt.TextField txtIdLibro;
    private java.awt.TextField txtIdPrestamo;
    private java.awt.TextField txtIdUser;
    // End of variables declaration//GEN-END:variables

    private void limpiar(){
        if(limpieza==false){
        txtIdPrestamo.setText("");
        txtIdUser.setText("");
        txtFSalida.setText("");
        txtIdLibro.setText("");
        listaEstado.setSelectedItem("Prestado");
        listaObSalida.setSelectedItem("Buenas Condiciones");
        listaObEntrada.setSelectedItem("");
        txtFEntrada.setDate(null);
        txtIdUser.requestFocus();
        lblResultado.setText("0 de 0");
        }
        else{
         txtIdLibro.setText("");
        listaEstado.setSelectedItem("Prestado");
        listaObSalida.setSelectedItem("Buenas Condiciones");
        listaObEntrada.setSelectedItem("");
        txtFEntrada.setDate(null);
        txtIdLibro.requestFocus();
                lblResultado.setText("0 de 0");

        }
        limpieza=false;

        
    }
   
   
}
