/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import com.mysql.jdbc.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import proyecto.Conexion;

/**
 *
 * @author TOSHIBA
 */
public class ModuloAlumnos extends javax.swing.JFrame {
Conexion db = new Conexion();
            Connection cn = db.MySQLConnect();
    PreparedStatement pst=null;
    ResultSet r = null;
     private int cont = 0;
 private int cont1 = 0;
 private int valor;
    /**
     * Creates new form NewJFrame
     */
    public ModuloAlumnos() {
        initComponents();
        setTitle("Modulo Usuarios");
        setLocationRelativeTo(null);
        txtNombreUser.requestFocus();
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlC = new javax.swing.JPanel();
        lblTitulo = new java.awt.Label();
        PnlDatosG = new javax.swing.JPanel();
        lblIDUser = new java.awt.Label();
        txtIdUser = new java.awt.TextField();
        lblNombre = new java.awt.Label();
        txtNombreUser = new java.awt.TextField();
        lblApPaterno = new java.awt.Label();
        txtApPaterno = new java.awt.TextField();
        lblApMaterno = new java.awt.Label();
        txtApMaterno = new java.awt.TextField();
        lblEdad = new java.awt.Label();
        txtEdad = new java.awt.TextField();
        pnlDomicilio = new javax.swing.JPanel();
        lblCalle = new java.awt.Label();
        txtCalle = new java.awt.TextField();
        lblColonia = new java.awt.Label();
        txtColonia = new java.awt.TextField();
        lblCP = new java.awt.Label();
        txtCP = new java.awt.TextField();
        PnlContacto = new javax.swing.JPanel();
        lblTel1 = new java.awt.Label();
        txtTel1 = new java.awt.TextField();
        lblTel2 = new java.awt.Label();
        txtTel2 = new java.awt.TextField();
        lblEmail = new java.awt.Label();
        txtEmail = new java.awt.TextField();
        pnlControl = new javax.swing.JPanel();
        btnIngresar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        pnlBuscar = new javax.swing.JPanel();
        txtBuscar = new java.awt.TextField();
        btnBuscar = new javax.swing.JButton();
        lblObBuscar = new java.awt.Label();
        btnPrim = new javax.swing.JButton();
        btnUlt = new javax.swing.JButton();
        btnSig = new javax.swing.JButton();
        btnAnt = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();
        menuPrincipal = new javax.swing.JMenuBar();
        menuUsuarios = new javax.swing.JMenu();
        SubmenuRegresar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        submenuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        pnlC.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblTitulo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblTitulo.setText("Usuarios");

        PnlDatosG.setBackground(new java.awt.Color(204, 255, 204));
        PnlDatosG.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Datos personales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 0, 204))); // NOI18N

        lblIDUser.setText("ID del Usuario:");

        txtIdUser.setEditable(false);
        txtIdUser.setEnabled(false);

        lblNombre.setText("Nombre:");

        lblApPaterno.setText("Apellido paterno:");

        lblApMaterno.setText("Apellido materno:");

        lblEdad.setText("Edad:");

        javax.swing.GroupLayout PnlDatosGLayout = new javax.swing.GroupLayout(PnlDatosG);
        PnlDatosG.setLayout(PnlDatosGLayout);
        PnlDatosGLayout.setHorizontalGroup(
            PnlDatosGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlDatosGLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(PnlDatosGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblApMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblApPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PnlDatosGLayout.createSequentialGroup()
                        .addGroup(PnlDatosGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIDUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(PnlDatosGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreUser, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdUser, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        PnlDatosGLayout.setVerticalGroup(
            PnlDatosGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlDatosGLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(PnlDatosGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIdUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIDUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlDatosGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombreUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlDatosGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtApPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblApPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlDatosGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtApMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblApMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlDatosGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pnlDomicilio.setBackground(new java.awt.Color(204, 255, 204));
        pnlDomicilio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Domicilio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 0, 204))); // NOI18N

        lblCalle.setText("Calle:");

        lblColonia.setText("Colonia:");

        lblCP.setText("Código postal");

        javax.swing.GroupLayout pnlDomicilioLayout = new javax.swing.GroupLayout(pnlDomicilio);
        pnlDomicilio.setLayout(pnlDomicilioLayout);
        pnlDomicilioLayout.setHorizontalGroup(
            pnlDomicilioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDomicilioLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnlDomicilioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblColonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(pnlDomicilioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtColonia, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCP, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        pnlDomicilioLayout.setVerticalGroup(
            pnlDomicilioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDomicilioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDomicilioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDomicilioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtColonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblColonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDomicilioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        PnlContacto.setBackground(new java.awt.Color(204, 255, 204));
        PnlContacto.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Infornación de contacto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 0, 204))); // NOI18N

        lblTel1.setText("Teléfono 1:");

        lblTel2.setText("Teléfono 2:");

        lblEmail.setText("E-mail:");

        javax.swing.GroupLayout PnlContactoLayout = new javax.swing.GroupLayout(PnlContacto);
        PnlContacto.setLayout(PnlContactoLayout);
        PnlContactoLayout.setHorizontalGroup(
            PnlContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlContactoLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(PnlContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PnlContactoLayout.createSequentialGroup()
                        .addComponent(lblTel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(PnlContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PnlContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtTel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                .addComponent(txtTel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        PnlContactoLayout.setVerticalGroup(
            PnlContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlContactoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlCLayout = new javax.swing.GroupLayout(pnlC);
        pnlC.setLayout(pnlCLayout);
        pnlCLayout.setHorizontalGroup(
            pnlCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCLayout.createSequentialGroup()
                .addGroup(pnlCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCLayout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PnlDatosG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PnlContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        pnlCLayout.setVerticalGroup(
            pnlCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(pnlCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCLayout.createSequentialGroup()
                        .addComponent(pnlDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PnlContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(pnlCLayout.createSequentialGroup()
                        .addComponent(PnlDatosG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pnlControl.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlControlLayout = new javax.swing.GroupLayout(pnlControl);
        pnlControl.setLayout(pnlControlLayout);
        pnlControlLayout.setHorizontalGroup(
            pnlControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlControlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnIngresar)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar)
                .addGap(18, 18, 18)
                .addComponent(btnActualizar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlControlLayout.setVerticalGroup(
            pnlControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlControlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar)
                    .addComponent(btnIngresar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlBuscar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lblObBuscar.setText("Dato a buscar:");

        btnPrim.setText("<<");
        btnPrim.setEnabled(false);
        btnPrim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimActionPerformed(evt);
            }
        });

        btnUlt.setText(">>");
        btnUlt.setEnabled(false);
        btnUlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltActionPerformed(evt);
            }
        });

        btnSig.setText(">");
        btnSig.setEnabled(false);
        btnSig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSigActionPerformed(evt);
            }
        });

        btnAnt.setText("<");
        btnAnt.setEnabled(false);
        btnAnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAntActionPerformed(evt);
            }
        });

        lblResultado.setText("0 de 0");

        javax.swing.GroupLayout pnlBuscarLayout = new javax.swing.GroupLayout(pnlBuscar);
        pnlBuscar.setLayout(pnlBuscarLayout);
        pnlBuscarLayout.setHorizontalGroup(
            pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBuscarLayout.createSequentialGroup()
                        .addGroup(pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBuscarLayout.createSequentialGroup()
                                .addComponent(lblObBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlBuscarLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(btnPrim)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAnt)
                                .addGap(18, 18, 18)
                                .addComponent(btnSig)))
                        .addGroup(pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBuscarLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(btnBuscar))
                            .addGroup(pnlBuscarLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnUlt))))
                    .addGroup(pnlBuscarLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        pnlBuscarLayout.setVerticalGroup(
            pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscar)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblObBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrim)
                    .addComponent(btnSig)
                    .addComponent(btnUlt)
                    .addComponent(btnAnt))
                .addGap(25, 25, 25))
        );

        menuUsuarios.setText("Opciones");

        SubmenuRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/regresar.jpg"))); // NOI18N
        SubmenuRegresar.setText("Regresar");
        SubmenuRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmenuRegresarActionPerformed(evt);
            }
        });
        menuUsuarios.add(SubmenuRegresar);
        menuUsuarios.add(jSeparator1);

        submenuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Exit.jpg"))); // NOI18N
        submenuSalir.setText("Salir");
        submenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenuSalirActionPerformed(evt);
            }
        });
        menuUsuarios.add(submenuSalir);

        menuPrincipal.add(menuUsuarios);

        setJMenuBar(menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(pnlControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pnlC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pnlBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(pnlBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmenuRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmenuRegresarActionPerformed
      Principal ventana=new Principal();
      ventana.setVisible(true);
      this.setVisible(false);
      
    }//GEN-LAST:event_SubmenuRegresarActionPerformed

    private void submenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_submenuSalirActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        // TODO add your handling code here:
      if(!txtBuscar.getText().equals("")){
          Buscar(); 
          txtBuscar.setText("");
      }       
      else{
                  JOptionPane.showMessageDialog(null, "No ingreso nada a buscar", "Error",0);

      }
    }//GEN-LAST:event_btnBuscarActionPerformed
private void Ingresar(){
    BuscarID();
    try {
        pst= cn.prepareStatement("INSERT INTO `persona`( `nombre`, `A_paterno`, `A_materno`, `Edad`, `Calle`, `Colonia`, `CP`, `Email`, `Telefono`, `Telefono_2`) VALUES  (?,?,?,?,?,?,?,?,?,?)");
        pst.setString(1, txtNombreUser.getText());
        pst.setString(2, txtApPaterno.getText());
        pst.setString(3, txtApMaterno.getText());
        pst.setInt(4, Integer.parseInt(txtEdad.getText()));
        pst.setString(5, txtCalle.getText());
        pst.setString(6,txtColonia.getText() );
        pst.setInt(7, Integer.parseInt(txtCP.getText()));
        pst.setString(8, txtEmail.getText());
        pst.setString(9, txtTel1.getText());
        pst.setString(10, txtTel2.getText());
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null,"Exito al ingresar datos con un id: "+(valor+1), "Exito", 1);
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "Complete los campos", "Error",0);
        Logger.getLogger(ModuloAlumnos.class.getName()).log(Level.SEVERE, null, ex);
    }
}
public void Buscar(){
     try {
            // TODO add your handling code here:
            pst = cn.prepareStatement("SELECT * FROM `persona` WHERE `idPersona` LIKE ? OR `nombre`LIKE ?");
            //(txtBuscar.getText())
            String vr = "%" + txtBuscar.getText() + "%";
            pst.setString(1, txtBuscar.getText());
            pst.setString(2, vr);
            r = pst.executeQuery();

            //ResultSet res = new Data();
            cont = 0;
            while (r.next()) {
                cont++;

                /* Pruebas Manuales 
          
                 */
            }
            if (cont == 0) {
                JOptionPane.showMessageDialog(null, "No se encontro algun resutaldo con la referencia " + txtBuscar.getText(), "Error", 0);
                Limpiar();
            
            } else {
                if (r.first()) {
                    cont1 = 1;
                    Campos();

                
                }
                inhabilitar();
            }
        } catch (SQLException ex) {
            Logger.getLogger(ModuloLibros.class.getName()).log(Level.SEVERE, null, ex);
        }


}
private void  BuscarID(){
    try {
        pst=cn.prepareStatement("SELECT `idPersona`FROM `persona`");
        r=pst.executeQuery();
        r.last();
                 valor=Integer.parseInt(r.getString("idPersona"));

    } catch (SQLException ex) {
        Logger.getLogger(ModuloAlumnos.class.getName()).log(Level.SEVERE, null, ex);
    }
    
}
    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
    if(txtIdUser.getText().equals("")){       
      
        Ingresar();
        
}  else{
         JOptionPane.showMessageDialog(null, "Usuario existente", "Error", 0);
           cont=0;
      inhabilitar();

        }
    Limpiar();
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnPrimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimActionPerformed
    try {
        // TODO add your handling code here:
        if(r.first()){
            cont1=1;
            Campos();
            /*<<*/
        }
        inhabilitar();
    } catch (SQLException ex) {
        Logger.getLogger(ModuloAlumnos.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btnPrimActionPerformed

    private void btnAntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAntActionPerformed
    try {
        // TODO add your handling code here:
        if(r.previous()){
            cont1--;
            Campos();
            
                /*<*/
        }
        inhabilitar();
    } catch (SQLException ex) {
        Logger.getLogger(ModuloAlumnos.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btnAntActionPerformed

    private void btnSigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSigActionPerformed
  
    try {
        // TODO add your handling code here:
        if(r.next()){
            cont1++;
            Campos();
                /*>*/
        }
        inhabilitar();
    } catch (SQLException ex) {
        Logger.getLogger(ModuloAlumnos.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    }//GEN-LAST:event_btnSigActionPerformed

    private void btnUltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltActionPerformed
    try {
        // TODO add your handling code here:
        if(r.last()){
            cont1=cont;
            Campos();
            /*>>*/
        }
        inhabilitar();
    } catch (SQLException ex) {
        Logger.getLogger(ModuloAlumnos.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btnUltActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
            try {
               int msg= JOptionPane.showConfirmDialog(null, "Desea Eliminar", "Eliminar",JOptionPane.OK_CANCEL_OPTION);
       if(msg==JOptionPane.OK_OPTION && !txtIdUser.getText().equals("") ){
            
            pst=cn.prepareStatement("DELETE FROM `persona` WHERE `IdPersona` = ?");
            
            pst.setString(1, txtIdUser.getText());
           
            pst.executeUpdate();
                        JOptionPane.showMessageDialog(null, "Eliminado", "Ok", 1);

            Limpiar();
       }
        else{
                      JOptionPane.showMessageDialog(null, "Verifique informacíon a eliminar","Error",0);

       }
       cont=0;
       inhabilitar();
        } catch (SQLException ex) {
            Logger.getLogger(ModuloLibros.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
          
           if(!txtIdUser.getText().equals("")){
               pst = cn.prepareStatement("UPDATE `persona` SET `nombre`=?,"
                       + "`A_paterno`=?,`A_materno`=?,`Edad`=?,`Calle`=?,"
                       + "`Colonia`=?,`CP`=?,`Email`=?,`Telefono`=?,`Telefono_2`=? "
                       + "WHERE  `idPersona` like ?");
           
       

                pst.setString(1, txtNombreUser.getText());
                pst.setString(2, txtApPaterno.getText());
                pst.setString(3, txtApMaterno.getText());
                pst.setInt(4, Integer.parseInt(txtEdad.getText()));
                pst.setString(5, txtCalle.getText());
                pst.setString(6, txtColonia.getText());
                pst.setInt(7, Integer.parseInt(txtCP.getText()));
                pst.setString(8, txtEmail.getText());
                pst.setString(9, txtTel1.getText());
                pst.setString(10, txtTel2.getText());
                pst.setInt(11, Integer.parseInt(txtIdUser.getText()));
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Los datos se modificaron correctamente", "Ok", 1);
                 Limpiar();
           }
           else{
                               JOptionPane.showMessageDialog(null, "Verifique los datos a Actualizar", "Error", 0);

           }
              cont=0;
       inhabilitar();
         } catch (SQLException ex) {
            Logger.getLogger(ModuloLibros.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModuloAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModuloAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModuloAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModuloAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModuloAlumnos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlContacto;
    private javax.swing.JPanel PnlDatosG;
    private javax.swing.JMenuItem SubmenuRegresar;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAnt;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnPrim;
    private javax.swing.JButton btnSig;
    private javax.swing.JButton btnUlt;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private java.awt.Label lblApMaterno;
    private java.awt.Label lblApPaterno;
    private java.awt.Label lblCP;
    private java.awt.Label lblCalle;
    private java.awt.Label lblColonia;
    private java.awt.Label lblEdad;
    private java.awt.Label lblEmail;
    private java.awt.Label lblIDUser;
    private java.awt.Label lblNombre;
    private java.awt.Label lblObBuscar;
    private javax.swing.JLabel lblResultado;
    private java.awt.Label lblTel1;
    private java.awt.Label lblTel2;
    private java.awt.Label lblTitulo;
    private javax.swing.JMenuBar menuPrincipal;
    private javax.swing.JMenu menuUsuarios;
    private javax.swing.JPanel pnlBuscar;
    private javax.swing.JPanel pnlC;
    private javax.swing.JPanel pnlControl;
    private javax.swing.JPanel pnlDomicilio;
    private javax.swing.JMenuItem submenuSalir;
    private java.awt.TextField txtApMaterno;
    private java.awt.TextField txtApPaterno;
    private java.awt.TextField txtBuscar;
    private java.awt.TextField txtCP;
    private java.awt.TextField txtCalle;
    private java.awt.TextField txtColonia;
    private java.awt.TextField txtEdad;
    private java.awt.TextField txtEmail;
    private java.awt.TextField txtIdUser;
    private java.awt.TextField txtNombreUser;
    private java.awt.TextField txtTel1;
    private java.awt.TextField txtTel2;
    // End of variables declaration//GEN-END:variables
private void Limpiar(){
    txtIdUser.setText("");
    txtNombreUser.setText("");
         txtApPaterno.setText("");
         txtApMaterno.setText("");
         txtEdad.setText("");
         txtCalle.setText("");
        txtColonia.setText("");
         txtCP.setText("");
         txtEmail.setText("");
        txtTel1.setText("");
        txtTel2.setText("");
        lblResultado.setText("0 de 0");

    
}

    public  void inhabilitar() {
        try {
            if (cont <= 1) {
                btnUlt.setEnabled(false);
                btnPrim.setEnabled(false);
                btnAnt.setEnabled(false);
                btnSig.setEnabled(false);
            } else {
                if (r.isFirst()) {
                    btnUlt.setEnabled(true);
                    btnPrim.setEnabled(false);
                    btnAnt.setEnabled(false);
                    btnSig.setEnabled(true);
                } else {
                    if (r.isLast()) {
                        btnUlt.setEnabled(false);
                        btnPrim.setEnabled(true);
                        btnAnt.setEnabled(true);
                        btnSig.setEnabled(false);
                    } else{
                        btnUlt.setEnabled(true);
                        btnPrim.setEnabled(true);
                        btnAnt.setEnabled(true);
                        btnSig.setEnabled(true);
                    }
                   
                }
            }

        } catch (SQLException ex) {
            Logger.getLogger(ModuloLibros.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void Campos(){
    try {
        txtIdUser.setText(r.getString("idPersona"));
        txtNombreUser.setText(r.getString("nombre"));
        txtApPaterno.setText(r.getString("A_paterno"));
        txtApMaterno.setText(r.getString("A_materno"));
       txtEdad.setText(r.getString("Edad"));
       txtCalle.setText(r.getString("Calle"));
       txtColonia.setText(r.getString("Colonia"));
         txtCP.setText(r.getString("CP"));
         txtEmail.setText(r.getString("Email"));
        txtTel1.setText(r.getString("Telefono"));
        txtTel2.setText(r.getString("Telefono_2"));
                    lblResultado.setText(cont1 + " de " + cont);

    } catch (SQLException ex) {
        Logger.getLogger(ModuloAlumnos.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
}
