/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import javax.swing.*;


/**
 *
 * @author TOSHIBA
 */
public class Principal extends javax.swing.JFrame {

     
             /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        ImageIcon img=new ImageIcon(this.getClass().getResource("/Imagenes/Imagen principal.jpg"));
        //Dimension fondo= getSize();
        //drawImage(img.getImage(),0,0,fondo.height,fondo.width);
        ((JPanel)getContentPane()).setOpaque(false);
        JLabel fondo= new JLabel();
        fondo.setIcon(img);
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0,0,img.getIconWidth(),img.getIconHeight());
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField1 = new java.awt.TextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuModulos = new javax.swing.JMenu();
        submenuUsuario = new javax.swing.JMenuItem();
        submenuFormato = new javax.swing.JMenuItem();
        submenuLibros = new javax.swing.JMenuItem();
        menuPrincipal = new javax.swing.JMenu();
        submenuSalir = new javax.swing.JMenuItem();

        textField1.setText("textField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Principal");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setResizable(false);

        menuModulos.setText("Modulos");

        submenuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/User_converted.jpg"))); // NOI18N
        submenuUsuario.setText("Usuario");
        submenuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenuUsuarioActionPerformed(evt);
            }
        });
        menuModulos.add(submenuUsuario);

        submenuFormato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/formato.jpg"))); // NOI18N
        submenuFormato.setText("Formato Prestamo/Devolución");
        submenuFormato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenuFormatoActionPerformed(evt);
            }
        });
        menuModulos.add(submenuFormato);

        submenuLibros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/libro.jpg"))); // NOI18N
        submenuLibros.setText("Libros");
        submenuLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenuLibrosActionPerformed(evt);
            }
        });
        menuModulos.add(submenuLibros);

        jMenuBar1.add(menuModulos);

        menuPrincipal.setText("Opciones");

        submenuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Exit.jpg"))); // NOI18N
        submenuSalir.setText("Salir");
        submenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenuSalirActionPerformed(evt);
            }
        });
        menuPrincipal.add(submenuSalir);

        jMenuBar1.add(menuPrincipal);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 621, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 156, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submenuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuUsuarioActionPerformed
        // TODO add your handling code here:
        ModuloAlumnos ventana=new ModuloAlumnos();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_submenuUsuarioActionPerformed

    private void submenuLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuLibrosActionPerformed
        // TODO add your handling code here:
        ModuloLibros libro=new ModuloLibros();
        libro.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_submenuLibrosActionPerformed

    private void submenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuSalirActionPerformed
        // TODO add your handling code here:
            System.exit(0);
    }//GEN-LAST:event_submenuSalirActionPerformed

    private void submenuFormatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuFormatoActionPerformed
        // TODO add your handling code here:
        ModuloFormato vent = new ModuloFormato();
        vent.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_submenuFormatoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuModulos;
    private javax.swing.JMenu menuPrincipal;
    private javax.swing.JMenuItem submenuFormato;
    private javax.swing.JMenuItem submenuLibros;
    private javax.swing.JMenuItem submenuSalir;
    private javax.swing.JMenuItem submenuUsuario;
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables

}
